# @package _global_

dataset_name: 4dr_00185_smpl

dataset:
  name: 4DressMulticam
  root_dir: "../data_lx/datasets/4Dress/00185"

  train_subject: Take7
  test_subject: Take8
  style: Inner
  model_type: smpl
  train_frames: [ 0, 180, 1 ]
  val_frames: [ 0, 130, 1 ]
  # train_frames: [ 0, 15, 1 ]
  # val_frames: [ 0, 15, 1 ]
  test_frames:
    pose: [ 0, 130, 1 ]
    all:  [ 0, 130, 1 ]
  predict_frames: [0, 0, 1]
  camera_idx_train: ['0004', '0028']
  camera_idx_val: '0004'
  img_hw:
    - 1280
    - 940

  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  random_garm_init: true