# @package _global_

rigid_name: mlp_field_smplx

model:
  deformer:
    rigid:
    # same network different parameters
      name: skinning_field_smplx

      lambda_knn_res: 0.0
      distill: false
      res: 64
      z_ratio: 4
      d_out: 59
      soft_blend: 20
      n_reg_pts: 2048
      skinning_network:
        otype: VanillaMLP
        n_neurons: 128
        n_hidden_layers: 4
        skip_in: []
        cond_in: []
        multires: 0

opt:
  lambda_skinning: [10,1000,0.1]
  rigid_lr: 1e-4